object CoreVersions {
    const val KOTLIN = "1.3.61"
    const val KOIN = "2.0.1"
    const val PLAY_SERVICE = "19.0.0"
    const val APP_COMPACT = "1.1.0"
    const val NAVIGATION = "2.1.0"
    const val LEGACY = "1.0.0"
    const val MATERIAL = "1.1.0-alpha05"
    const val CONSTRAINT_LAYOUT = "2.0.0-beta4"
    const val CORE_KTX = "1.1.0"
    const val LIFECYCLE_EXT = "2.1.0"
    const val LIFECYCLE_VIEW_MODEL_KTX = "2.1.0"
    const val VECTOR_DRAWABLE = "1.1.0"
    const val SDP = "1.0.4"
    const val OBJECTBOX = "2.5.0"
    const val GRADEL_BUILD_TOOLS = "3.5.3"
    const val RETROFIT = "2.5.0"
    const val RETROFIT_GSON = "2.5.0"
    const val LOGGING = "3.11.0"
    const val STETHO = "1.5.1"
    const val KTLINT_GRADLE = "9.1.1"
    const val DETEKT = "1.4.0"
}